# Generated by Django 3.2.7 on 2021-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_time', models.DateTimeField()),
                ('entered_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('glucose_level', models.IntegerField()),
            ],
            options={
                'ordering': ['observed_time'],
            },
        ),
    ]
