# Generated by Django 3.2.7 on 2021-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='observed_date',
            field=models.DateField(default='2021-09-17'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reading',
            name='observed_time',
            field=models.TimeField(),
        ),
    ]
