# Generated by Django 3.2.7 on 2021-10-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_auto_20210917_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['observed_date', 'observed_time']},
        ),
        migrations.AddField(
            model_name='reading',
            name='observed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='weight_at_reading',
            field=models.IntegerField(null=True),
        ),
    ]
