# Generated by Django 3.2.7 on 2021-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_auto_20211027_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='age_at_reading',
            field=models.IntegerField(null=True),
        ),
    ]
