# Generated by Django 3.2.7 on 2021-11-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_reading_age_at_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-observed_datetime']},
        ),
        migrations.AddField(
            model_name='reading',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
