# Generated by Django 3.2.7 on 2021-10-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_userdetail_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
