# Generated by Django 3.2.7 on 2021-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_userdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='default_timespan',
            field=models.IntegerField(default=7),
        ),
    ]
