import Head from 'next/head';
import Image from 'next/image';
import Container from '@material-ui/core/Container';
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
import { makeStyles } from '@material-ui/core/styles';
import Link from 'next/link';
import { useRouter } from 'next/Router';

const useStyles = makeStyles(theme => ({
  root: {
    '& .MuiTextField-root': {
      margin: theme.spacing(1),
      width: 200
    }
  }
}));

export default function Home() {
  const classes = useStyles();
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Sugar Chart</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='minimum-scale=1, initial-scale=1, width=device-width'
        />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
        />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />
      </Head>

      <main>
        <Container maxwidth='sm'>
          <h1>Sugar Chart</h1>
          <form noValidate autoComplete='off'>
            <TextField
              required
              id='username'
              label='Required'
              defaultValue='Username'
              variant='filled'
              color='secondary'
              fullWidth
            />
            <TextField
              id='password'
              label='Password'
              type='password'
              autoComplete='current-password'
              variant='filled'
              margin='normal'
              color='secondary'
              fullWidth
            />
            <Button
              variant='contained'
              color='primary'
              onClick={e => {
                e.preventDefault();
                router.push('menu');
              }}
            >
              Sign In
            </Button>
          </form>
        </Container>
      </main>
    </div>
  );
}
