import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Container from '@material-ui/core/Container';
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
import { makeStyles } from '@material-ui/core/styles';
import Link from 'next/link';

const useStyles = makeStyles((theme) => ({
  root: {
    '& .MuiTextField-root': {
      margin: theme.spacing(1),
      width: 200,
    },
  },
}));

export default function Home() {

  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>Sugar Chart</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>

      <main>
        <Container maxwidth="sm">
          <div>Header bar</div>
          <div>Avg sugar reading</div>
          <div>charts</div>
          <div>new entry</div>
        </Container>
      </main>
    </div>
  )
}
