import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/Router';

import HeaderBar from '../components/HeaderBar';
import Profile from '../components/Profile';

export default function ProfilePage() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Sugar Chart</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='minimum-scale=1, initial-scale=1, width=device-width'
        />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
        />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />
      </Head>

      <main>
        <HeaderBar/>
        <Profile/>
      </main>
    </div>
  );
}
